version: "3.8"
services:
  freeswitch:
    build: .
    cap_add:
      - SYS_NICE
    container_name: freeswitch
    restart: always
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "5080:5080/udp"
      - "5080:5080/tcp"
      - "8021:8021"
