version: "3.8"
services:
  freeswitch:
    build: .
    cap_add:
      - SYS_NICE
    container_name: freeswitch
    restart: always
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "5080:5080/udp"
      - "5080:5080/tcp"
      - "8021:8021"
    # volumes:
    #   - "D:\\Omi\\Freeswitch\\conf:/usr/local/freeswitch/conf"
    #   - "D:\\Omi\\Freeswitch\\logs:/usr/local/freeswitch/log"
    #   - "D:\\Omi\\Freeswitch\\recordings:/usr/local/freeswitch/recordings"

# <configuration name="event_socket.conf" description="Socket Client">
#   <settings>
#     <param name="listen-ip" value="0.0.0.0"/>
#     <param name="listen-port" value="8021"/>
#     <param name="password" value="ClueCon"/>
#     <param name="apply-inbound-acl" value="lan"/>
#     <param name="tls" value="false"/>
#     <param name="ip-version" value="4"/>
#   </settings>
# </configuration>